/* ============================================================
   Procurement price list — auto-generated from
   "procurement price BOM.xlsx" on 06 Jul 2026.
   Rates are PURCHASE prices (no margin). Used by the BOM view;
   items not listed here fall back to quotation rates.
   ============================================================ */

const PROCUREMENT_RATES = {
  "360 degree wheel": { rate: 55.0, unit: "pc" },
  "abs black dotted": { rate: 10.0, unit: "sqft" },
  "abs silver checkers": { rate: 10.0, unit: "sqft" },
  "abs silver dotted": { rate: 10.0, unit: "sqft" },
  "acp 4mm orange": { rate: 66.08, unit: "sqft" },
  "acp 4mm silver black": { rate: 68.09, unit: "sqft" },
  "acp b2b 4mm (2250x1220)": { rate: 41.0, unit: "sqft" },
  "acp b2b 4mm (2440x1220)": { rate: 41.0, unit: "sqft" },
  "acp black 2mm": { rate: 45.0, unit: "sqft" },
  "acp black 3mm": { rate: 56.0, unit: "sqft" },
  "acp black 4mm": { rate: 68.0, unit: "sqft" },
  "acp deep gray 4mm 2320x1220": { rate: 64.03, unit: "sqft" },
  "acp deep gray 4mm 2820x1220": { rate: 64.01, unit: "sqft" },
  "acp silver 2mm": { rate: 45.0, unit: "sqft" },
  "acp silver 3mm": { rate: 56.0, unit: "sqft" },
  "acp silver 4mm": { rate: 68.0, unit: "sqft" },
  "auminium plain sheet": { rate: 132.0, unit: "sqft" },
  "big ball corner - 6 hole - ms (4.8x25mm)": { rate: 24.5, unit: "pc", weightKg: 0.0595 },
  "big hinges black (regular) (4.5x18mm)": { rate: 42.0, unit: "pc", weightKg: 0.068 },
  "big hinges chrome(regular) (4.5x18mm)": { rate: 40.0, unit: "pc", weightKg: 0.07 },
  "big hinges jumbo - ms (4.5x18mm)": { rate: 95.0, unit: "pc", weightKg: 0.25 },
  "briefcase handle black": { rate: 60.0, unit: "pc", weightKg: 0.0625 },
  "butterfly hinges - small ( with hold) - ms": { rate: 4.0, unit: "pc", weightKg: 0.0035 },
  "butterfly lock 2x2 black - ms": { rate: 60.0, unit: "pc", weightKg: 0.115 },
  "butterfly lock 2x2 chrome - ms": { rate: 60.0, unit: "pc", weightKg: 0.115 },
  "butterfly lock 4x4 black": { rate: 105.0, unit: "pc", weightKg: 0.213 },
  "butterfly lock 4x4 chrome": { rate: 110.0, unit: "pc", weightKg: 0.213 },
  "butterfly lock 7x4 black - ss": { rate: 280.0, unit: "pc", weightKg: 0.433 },
  "butterfly lock 7x4 chrome - ms": { rate: 158.0, unit: "pc", weightKg: 0.452 },
  "butterfly lock 7x4 chrome - ss": { rate: 235.0, unit: "pc", weightKg: 0.429 },
  "c channel": { rate: 7.0, unit: "ft" },
  "casting handle black heavy duty - 2 screw": { rate: 100.0, unit: "pc", weightKg: 0.112 },
  "casting lock black with branding": { rate: 112.85, unit: "pc", weightKg: 0.084 },
  "casting lock black without branding": { rate: 100.0, unit: "pc", weightKg: 0.084 },
  "casting lock silver with branding": { rate: 105.0, unit: "pc", weightKg: 0.087 },
  "casting lock silver without branding": { rate: 107.21, unit: "pc", weightKg: 0.087 },
  "castor wheel with break 1.5\"": { rate: 60.0, unit: "pc", weightKg: 0.171 },
  "castor wheel with break 2\"": { rate: 90.0, unit: "pc", weightKg: 0.265 },
  "castor wheel with break 4\"": { rate: 165.0, unit: "pc", weightKg: 0.73 },
  "castor wheel with break 5\"": { rate: 210.0, unit: "pc", weightKg: 0.812 },
  "corner wheel": { rate: 160.0, unit: "pc" },
  "curve handle black": { rate: 150.0, unit: "pc", weightKg: 0.053 },
  "curve handle silver": { rate: 150.0, unit: "pc", weightKg: 0.053 },
  "d hook big for belt ( 2 hole)": { rate: 5.0, unit: "pc" },
  "d hook for belt": { rate: 3.0, unit: "pc" },
  "d leg": { rate: 3.25, unit: "pc", weightKg: 0.009 },
  "dl profile corner black - 4mm (3x16)": { rate: 8.0, unit: "pc", weightKg: 0.0011 },
  "dl profile corner chrome - 4mm (3x16)": { rate: 7.0, unit: "pc", weightKg: 0.001 },
  "door hinges - ms (4.8x25mm)": { rate: 9.5, unit: "pc", weightKg: 0.0535 },
  "double angle profile 9mm": { rate: 54.0, unit: "ft" },
  "double angle profile black 4mm": { rate: 23.0, unit: "ft" },
  "double angle profile silver 4mm": { rate: 23.0, unit: "ft" },
  "double angle profile without coating 4mm": { rate: 21.0, unit: "ft" },
  "drawer plain handle - ss": { rate: 25.0, unit: "pc", weightKg: 0.032 },
  "f profile black - 720mm - 4mm": { rate: 13.0, unit: "pc" },
  "female profile 9mm": { rate: 28.0, unit: "ft" },
  "female profile black 2mm": { rate: 5.0, unit: "ft" },
  "female profile black 4mm": { rate: 13.0, unit: "ft" },
  "female profile silver 2mm": { rate: 5.0, unit: "ft" },
  "female profile silver 4mm": { rate: 13.0, unit: "ft" },
  "female profile without coating 2mm": { rate: 4.0, unit: "ft" },
  "female profile without coating 4mm": { rate: 9.0, unit: "ft" },
  "full black handle": { rate: 40.0, unit: "pc", weightKg: 0.08 },
  "full black heavy duty handle - 1 screw": { rate: 100.0, unit: "pc", weightKg: 0.204 },
  "heavy duty retractable spring handle - ms": { rate: 100.0, unit: "pc", weightKg: 0.181 },
  "inside fixed wheel - pvc": { rate: 135.0, unit: "pc", weightKg: 0.205 },
  "inside fixed wheel - ss": { rate: 160.0, unit: "pc", weightKg: 0.026 },
  "inside heavy duty trolley l profile": { rate: 550.0, unit: "pc", weightKg: 1.77 },
  "inside trolley for l profile": { rate: 516.0, unit: "pc", weightKg: 0.583 },
  "inside trolley for r profile": { rate: 516.0, unit: "pc", weightKg: 0.507 },
  "l corner for small double angle profile - 4 hole - black - 4mm (3x16)": { rate: 8.0, unit: "pc", weightKg: 0.006 },
  "l corner- 4 hole - wooden case (4.8x25mm)": { rate: 5.0, unit: "pc", weightKg: 0.0175 },
  "l corner- 6 hole - wooden case (4.8x25mm)": { rate: 6.5, unit: "pc", weightKg: 0.002 },
  "l hinges corner - chrome -ms": { rate: 35.0, unit: "pc", weightKg: 0.0695 },
  "l patti 12mm": { rate: 9.0, unit: "ft" },
  "l patti 20mm": { rate: 29.0, unit: "ft" },
  "l support black - 4mm (4.8x12.7)": { rate: 4.15, unit: "pc", weightKg: 0.011 },
  "l support chrome - 6 hole - ss": { rate: 22.0, unit: "pcs", weightKg: 0.056 },
  "l wheel plastic": { rate: 35.0, unit: "pc" },
  "laminate sheet black": { rate: 15.0, unit: "sqft" },
  "m profile black - 720mm - 4mm": { rate: 13.0, unit: "pc" },
  "m/f black - f - ss - 2mm": { rate: 7.5, unit: "pc", weightKg: 0.004 },
  "m/f black - f - ss - 4mm": { rate: 9.5, unit: "pc", weightKg: 0.0055 },
  "m/f black - m - ss - 2mm": { rate: 7.5, unit: "pc", weightKg: 0.0035 },
  "m/f black - m - ss - 4mm": { rate: 9.5, unit: "pc", weightKg: 0.0055 },
  "m/f chrome - f - ss - 2mm": { rate: 6.5, unit: "pc", weightKg: 0.003 },
  "m/f chrome - f - ss - 4mm": { rate: 9.0, unit: "pc", weightKg: 0.005 },
  "m/f chrome - m - ss - 2mm": { rate: 6.5, unit: "pc", weightKg: 0.003 },
  "m/f chrome - m - ss - 4mm": { rate: 9.0, unit: "pc", weightKg: 0.005 },
  "male profile 9mm": { rate: 28.0, unit: "ft" },
  "male profile black 2mm": { rate: 5.25, unit: "ft" },
  "male profile black 4mm": { rate: 13.0, unit: "ft" },
  "male profile silver 2mm": { rate: 5.25, unit: "ft" },
  "male profile silver 4mm": { rate: 13.0, unit: "ft" },
  "male profile wihout coating 2mm": { rate: 4.25, unit: "ft" },
  "male profile without coating 4mm": { rate: 9.0, unit: "ft" },
  "mdf panel 1.5mm": { rate: 12.0, unit: "sqft" },
  "mdf panel 1.8mm": { rate: 12.0, unit: "sqft" },
  "mdf panel 3mm": { rate: 13.0, unit: "sqft" },
  "mdf panel 4mm": { rate: 13.0, unit: "sqft" },
  "medium ball corner (4.8x20mm)": { rate: 33.0, unit: "pc", weightKg: 0.0535 },
  "medium hinges - chrome - (ms)": { rate: 20.0, unit: "pc", weightKg: 0.011 },
  "new retractable handle": { rate: 33.0, unit: "pc", weightKg: 0.0735 },
  "number lock": { rate: 75.0, unit: "pc", weightKg: 0.03 },
  "outside trolley": { rate: 174.0, unit: "pc", weightKg: 0.72 },
  "outside trolley small": { rate: 174.0, unit: "pc", weightKg: 0.493 },
  "pad lock black": { rate: 48.0, unit: "pc", weightKg: 0.105 },
  "plywood 12mm": { rate: 40.0, unit: "sqft" },
  "plywood 18mm": { rate: 60.0, unit: "sqft" },
  "plywood 25mm": { rate: 80.0, unit: "sqft" },
  "plywood 25mm (6x4)": { rate: 80.0, unit: "sqft" },
  "plywood 25mm 7x4": { rate: 80.0, unit: "sqft" },
  "plywood 6mm": { rate: 28.0, unit: "sqft" },
  "plywood 8mm": { rate: 34.14, unit: "sqft" },
  "plywood 8mm 6x3": { rate: 32.0, unit: "sqft" },
  "plywood 8mm 6x4": { rate: 32.0, unit: "sqft" },
  "plywood 8mm 7x4": { rate: 32.0, unit: "sqft" },
  "power socket with switch": { rate: 38.0, unit: "pc", weightKg: 0.025 },
  "power socket without switch": { rate: 5.5, unit: "pc", weightKg: 0.006 },
  "r profile black 2mm": { rate: 17.0, unit: "ft" },
  "r profile black 4mm": { rate: 26.0, unit: "ft" },
  "r profile plastic connector - 2mm": { rate: 3.9, unit: "pc", weightKg: 0.0035 },
  "r profile plastic connector - 4mm": { rate: 3.9, unit: "pc", weightKg: 0.0035 },
  "r profile silver 2mm": { rate: 17.0, unit: "ft" },
  "r profile silver 4mm": { rate: 26.0, unit: "ft" },
  "r profile without coating 2mm": { rate: 14.0, unit: "ft" },
  "r profile without coating 4mm": { rate: 21.0, unit: "ft" },
  "r support chrome - ss - 4mm": { rate: 2.5, unit: "pc", weightKg: 0.006 },
  "regular corner ( vatka) chrome - ss - 4mm": { rate: 9.75, unit: "pc", weightKg: 0.015 },
  "regular corner (vatka) black - ss - 4mm": { rate: 8.75, unit: "pc", weightKg: 0.0155 },
  "regular lock with keys - black": { rate: 27.0, unit: "pc", weightKg: 0.031 },
  "regular lock with keys - chrome": { rate: 25.0, unit: "pc", weightKg: 0.031 },
  "regular retractable handle": { rate: 33.0, unit: "pc", weightKg: 0.0835 },
  "rocker switch": { rate: 7.0, unit: "pc", weightKg: 0.004 },
  "rubber bush 25x10": { rate: 5.75, unit: "pc", weightKg: 0.008 },
  "rubber bush 35x10": { rate: 7.5, unit: "pc", weightKg: 0.018 },
  "rubber bush 45x20": { rate: 12.0, unit: "pc", weightKg: 0.034 },
  "silver black handle": { rate: 40.0, unit: "pc", weightKg: 0.0735 },
  "silver black heavy duty handle - 1 screw": { rate: 100.0, unit: "pc", weightKg: 0.201 },
  "silver black medium duty handle - 1 screw": { rate: 100.0, unit: "pc", weightKg: 0.091 },
  "sliding wheel": { rate: 250.0, unit: "pc" },
  "small hinges ch(4 hole with hold) - ms": { rate: 4.0, unit: "pc", weightKg: 0.0035 },
  "small hinges chrome (regular) ss": { rate: 15.0, unit: "pc", weightKg: 0.0245 },
  "spring handle surface - ms - chrome": { rate: 62.0, unit: "pc", weightKg: 0.246 },
  "spring handle with tray - black": { rate: 85.0, unit: "pc", weightKg: 0.271 },
  "spring handle with tray - chrome": { rate: 70.0, unit: "pc", weightKg: 0.2795 },
  "spring handle with tray - ms - chrome": { rate: 52.0, unit: "pc", weightKg: 0.272 },
  "spring handle without tray black": { rate: 63.0, unit: "pc", weightKg: 0.1725 },
  "spring handle without tray chrome": { rate: 90.0, unit: "pc", weightKg: 0.1715 },
  "square butterfly small lock without keys - chrome": { rate: 8.0, unit: "pc", weightKg: 0.004 },
  "square lock small without keys - chrome": { rate: 2.5, unit: "pc", weightKg: 0.009 },
  "square lock with keys": { rate: 60.0, unit: "pc", weightKg: 0.02 },
  "square tube black 12x12 1300mm": { rate: 19.0, unit: "pc" },
  "square tube black 12x12 1370mm": { rate: 19.0, unit: "pc" },
  "square tube black 12x12 702mm": { rate: 19.0, unit: "pc" },
  "track hinges - ss": { rate: 75.0, unit: "pc", weightKg: 0.252 },
  "tray hines -4x4- ms": { rate: 175.0, unit: "pc", weightKg: 0.229 },
  "tray hinges - 7x4 - ms": { rate: 235.0, unit: "pcs", weightKg: 0.408 },
  "tube 12x12": { rate: 19.0, unit: "ft" },
  "very small hinges chrome": { rate: 3.0, unit: "pc", weightKg: 0.1 },
};

// Aliases: portal item labels that differ from the purchase-list names.
const PROCUREMENT_ALIASES = {
  "acp 4mm": "acp silver 4mm",
  "acp 3mm": "acp silver 3mm",
  "acp 2mm": "acp silver 2mm",
  "acp panel 4mm": "acp silver 4mm",
  "mdf panel 4mm 4mm": "mdf panel 4mm",
  "abs silver 2mm": "abs silver dotted",
  "abs black 2mm": "abs black dotted",
};

// Look up a procurement rate by item name. Returns { rate, unit } or null.
function procurementRate(name) {
  const norm = (s) => String(s || "").toLowerCase().replace(/\s+/g, " ").trim();
  const key = norm(name);
  if (PROCUREMENT_RATES[key]) return PROCUREMENT_RATES[key];
  const alias = PROCUREMENT_ALIASES[key];
  if (alias && PROCUREMENT_RATES[alias]) return PROCUREMENT_RATES[alias];
  // "Female Profile 9mm (Body)" -> "Female Profile 9mm"
  const stripped = norm(key.replace(/\s*\([^)]*\)\s*$/, ""));
  if (stripped !== key && PROCUREMENT_RATES[stripped]) return PROCUREMENT_RATES[stripped];
  return null;
}
